version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-management-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-management-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: task-management-backend
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=task_management
      - NODE_ENV=development
      - PORT=3002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - task-management-network

networks:
  task-management-network:

volumes:
  postgres-data:
